services:
  book-jpa-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: book-jpa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - book-jpa-postgres-data:/var/lib/postgresql/data
    ports:
      - "9090:5432"
    networks:
      - book-jpa-network

  book-jpa-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book-jpa-postgres:5432/book-jpa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - book-jpa-postgres
    networks:
      - book-jpa-network

volumes:
  book-jpa-postgres-data:
networks:
  book-jpa-network:
    driver: bridge